version: '3.1'

services:
  sentinel1:
    image: redis:7.0
    container_name: redis-sentinel-1
    ports:
      - "26379:26379"
    command: redis-sentinel /data/sentinel.conf
    volumes:
      - ./config/sentinel1:/data
  sentinel2:
    image: redis:7.0
    container_name: redis-sentinel-2
    ports:
      - "26380:26379"
    command: redis-sentinel /data/sentinel.conf
    volumes:
      - ./config/sentinel2:/data
  sentinel3:
    image: redis:7.0
    container_name: redis-sentinel-3
    ports:
      - "26381:26379"
    command: redis-sentinel /data/sentinel.conf
    volumes:
      - ./config/sentinel3:/data

networks:
  default:
    external: true
    name: redis-sentinel_default