version: '3.1'

services:
  redis1:
    image: redis:7.0
    container_name: cluster-redis-1
    command: redis-server --protected-mode no --cluster-enabled yes --cluster-config-file redis-node1.conf --bind "0.0.0.0"
    ports:
      - "7000:6379"
    volumes:
      - ./data/redis1:/data
    restart: always
  redis2:
    image: redis:7.0
    container_name: cluster-redis-2
    command: redis-server --protected-mode no --cluster-enabled yes --cluster-config-file redis-node2.conf --bind "0.0.0.0"
    ports:
      - "7001:6379"
    volumes:
      - ./data/redis2:/data
    restart: always
  redis3:
    image: redis:7.0
    container_name: cluster-redis-3
    command: redis-server --protected-mode no --cluster-enabled yes --cluster-config-file redis-node3.conf --bind "0.0.0.0"
    ports:
      - "7002:6379"
    volumes:
      - ./data/redis3:/data
    restart: always
  redis4:
    image: redis:7.0
    container_name: cluster-redis-4
    command: redis-server --protected-mode no --cluster-enabled yes --cluster-config-file redis-node4.conf --bind "0.0.0.0"
    ports:
      - "7003:6379"
    volumes:
      - ./data/redis4:/data
    restart: always
  redis5:
    image: redis:7.0
    container_name: cluster-redis-5
    command: redis-server --protected-mode no --cluster-enabled yes --cluster-config-file redis-node5.conf --bind "0.0.0.0"
    ports:
      - "7004:6379"
    volumes:
      - ./data/redis5:/data
    restart: always
  redis6:
    image: redis:7.0
    container_name: cluster-redis-6
    command: redis-server --protected-mode no --cluster-enabled yes --cluster-config-file redis-node6.conf --bind "0.0.0.0"
    ports:
      - "7005:6379"
    volumes:
      - ./data/redis6:/data
    restart: always